### ISSUE TITLE
sketch crashes when exporting with symbols

### ISSUE THREAD

**Issue by dfanchi** [sketch-hq/print-export-sketchplugin#17] opened 2019-10-04 08:32 UTC
I've Version 57.1 (83088) and it's enough to have one symbol used.

**Comment by Tafkadasoh** [comment] 2020-02-14 14:26
I have the same issue! And I can confirm that the presence of any symbol is the issue. When detaching all contents of all symbols, the export does not crash.

**Comment by bomberstudios** [comment] 2020-06-22 11:12
Seems to be working as expected in v1.0.10 of the plugin, so closing

**Closed as completed by bomberstudios** 2020-06-22 11:12 UTC
